### ISSUE TITLE
Improve Typescript chapter

### ISSUE THREAD

**Issue by alfonsograziano** [nearform/node-test-runner-workshop#18]
In [this video](https://www.youtube.com/watch?v=vICQMCS9AIY&ab_channel=AdventuresinNodeland-MatteoCollina), Matteo Collina explains how to use Typescript with the Node.js test runner. 

In our chapter, we're showing how to do it with the tsx `--loader`, but this solution doesn't work very well with test suites.
The solution proposed by Matteo sounds promising, I think is worth taking a look

**Comment by simoneb** [comment]
@bilalshareef can you please take a look at this one too?

**Comment by bilalshareef** [comment]
As per the video, there are couple of issues with the current approach using tsx `--loader`.
1. Running just `node --import=tsx --test` doesn't work. We have to specify the path or glob of file(s) to test.
2. It skips type checking.

A better approach/solution proposed by Matteo Collina in the video is to use a new npm package named [borp](https://www.npmjs.com/package/borp) written by himself which is a test runner on top of node:test. It is basically a wrapper to node:test which adds support for TypeScript.

Since this workshop is just about the node:test runner and borp is a third-party library in this case, we can stick with the current approach itself.

**Comment by simoneb** [comment]
Agreed, thanks for looking into this. I'll close this for now because I consider it out of scope for this workshop, but I'm equally confident that this feature may land into the test runner at some point, in which case we can incorporate it.
